### ISSUE TITLE
Looks like text on filters is being cut off

### ISSUE THREAD

**Issue by toomanysnipers** [mmolad/r-overwatch#20]
![text](https://cloud.githubusercontent.com/assets/19477823/15406845/09cb66b4-1e00-11e6-9ee9-d96cc2588e1a.PNG)

**Comment by mmolad** [comment]
Can I get a full screen screenshot on this?

**Comment by toomanysnipers** [comment]
![filters](https://cloud.githubusercontent.com/assets/19477823/15410694/15594bc8-1e13-11e6-9927-9b0ce6521ed3.PNG)
